/**
 * Non-removable disclaimer rendered on every screen with AI output.
 *
 * Constitution IV: every generated output must carry a disclaimer making
 * it explicit that (a) the output is generated by a tool not a lawyer,
 * (b) the output supports rather than replaces attorney review, and
 * (c) the attorney remains responsible for the final work product. This
 * component renders that disclaimer at App shell level so all routes
 * inherit it automatically — never `display: none` it, never gate it
 * behind a flag.
 */

export const DISCLAIMER_EYEBROW = 'AI-generated output — attorney review required';
export const DISCLAIMER_BODY =
  "Caveat AI supports, but does not replace, the lawyer's professional judgment.";

export function DisclaimerFooter(): JSX.Element {
  return (
    <footer
      className="border-t border-line bg-bg py-4 px-6 text-center shrink-0"
      data-testid="disclaimer-footer"
    >
      <p className="font-mono text-[10px] tracking-[0.18em] uppercase text-ink-muted">
        {DISCLAIMER_EYEBROW}
      </p>
      <p className="font-sans text-xs italic text-ink-muted mt-1">
        {DISCLAIMER_BODY}
      </p>
    </footer>
  );
}

export default DisclaimerFooter;
