"""Client-summary pipeline stage — the four-section plain-English memo.

Calls Ollama once to produce a four-field JSON memo for a non-lawyer
client, then attaches the constitutional disclaimer.

Constitution IV — Disclaimers are part of the product
-----------------------------------------------------
The disclaimer is a non-removable, server-side constant
(:data:`DISCLAIMER_TEXT`). The model NEVER generates it; the prompt in
:mod:`caveat.llm.prompts` explicitly forbids the model from authoring,
paraphrasing, or omitting one. This module is the single place the
disclaimer is attached, so the audit trail for "did this output ship with
a disclaimer" is one ``grep``.

Per Constitution I, all network I/O is funnelled through
:mod:`caveat.llm.ollama_client`. Per Constitution VI, malformed model
output is surfaced as a fallback memo with the disclaimer still attached
— the lawyer sees that the summary failed; we do not pretend it
succeeded.

Sprint 1 fixup-2: :func:`build_client_summary` now returns
``(ClientSummary, tuple[str, ...])`` instead of just ``ClientSummary``.
The original shape silently produced fallback prose for missing or
malformed fields with no signal to the caller, which violated
Constitution VI (the lawyer saw "(Not available...)" placeholders in the
response with no warning explaining why). The router merges the returned
warnings into the API response so the channel matches
:class:`caveat.pipeline.analyze.AnalysisResult`.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import asdict, dataclass

from caveat.llm import ollama_client
from caveat.llm.prompts import build_client_summary_prompt
from caveat.pipeline.validate_citations import Finding

DISCLAIMER_TEXT = (
    "This summary was generated by Caveat AI, an AI tool. It is intended to "
    "support, not replace, attorney review. The attorney remains responsible "
    "for the final work product."
)
"""The non-removable disclaimer, attached to every :class:`ClientSummary`.

Constitution IV: every generated output ships with this. There is no flag
to disable it; it is a default value on the dataclass field below."""

_FIELD_FALLBACK = "(Not available — model output incomplete.)"
_TOTAL_FALLBACK = "(Summary unavailable — model returned malformed output.)"
_MAX_RISKS = 3


@dataclass(slots=True, frozen=True)
class ClientSummary:
    """The four-section client-facing memo plus the constitutional disclaimer.

    ``biggest_risks`` holds up to :data:`_MAX_RISKS` strings (we trim if
    the model returns more). An empty tuple is acceptable: it means the
    model could not identify any material risks, which is a real signal
    and not a bug.
    """

    what_this_contract_is: str
    what_youre_committing_to: str
    biggest_risks: tuple[str, ...]
    recommendation: str
    disclaimer: str = DISCLAIMER_TEXT


def _coerce_text(value: object) -> str:
    """Return *value* as a non-empty string or :data:`_FIELD_FALLBACK`."""
    if isinstance(value, str) and value.strip():
        return value
    return _FIELD_FALLBACK


def _coerce_risks(value: object) -> tuple[str, ...]:
    """Coerce the model's ``biggest_risks`` field into at most :data:`_MAX_RISKS`."""
    if not isinstance(value, list):
        return ()
    risks: list[str] = []
    for item in value:
        if isinstance(item, str) and item.strip():
            risks.append(item)
        if len(risks) == _MAX_RISKS:
            break
    return tuple(risks)


def build_client_summary(
    findings: Iterable[Finding],
    contract_type: str,
    source_text: str,
) -> tuple[ClientSummary, tuple[str, ...]]:
    """Generate the client-facing memo for *contract_type* given *findings*.

    Returns ``(summary, warnings)`` where *warnings* is a tuple of strings
    that the router merges into :class:`caveat.routers.analyze.AnalyzeResponse`.
    The shape mirrors :class:`caveat.pipeline.analyze.AnalysisResult` for
    consistency.

    The findings are converted to plain dicts for the prompt (the model
    receives the same shape regardless of the dataclass implementation
    behind it). The disclaimer is attached unconditionally — even on
    malformed-JSON failure paths — because that is the constitutional
    invariant.

    Constitution VI fixup-2: emit a warning when the model returned
    malformed JSON (so the user sees why the four fields are placeholders)
    AND when individual fields fell back silently (so the user knows
    *which* field the model omitted).
    """
    findings_dicts = [asdict(f) for f in findings]
    prompt = build_client_summary_prompt(findings_dicts, contract_type, source_text)
    warnings: list[str] = []

    try:
        payload = ollama_client.generate_json(prompt)
    except ollama_client.OllamaInvalidJSONError:
        warnings.append(
            "Client summary: model returned malformed JSON. All four "
            "narrative fields are placeholders; rerun the analysis or "
            "fall back to attorney drafting."
        )
        return (
            ClientSummary(
                what_this_contract_is=_TOTAL_FALLBACK,
                what_youre_committing_to=_TOTAL_FALLBACK,
                biggest_risks=(),
                recommendation=_TOTAL_FALLBACK,
            ),
            tuple(warnings),
        )
    except ollama_client.OllamaTimeoutError as exc:
        # Sprint 2 fixup-3: the summary stage is the longest in the
        # pipeline (cold-start + long-context narrative generation can
        # exceed 200s on E4B). Pre-fixup, this exception bubbled to the
        # router as HTTP 500 with stack trace, violating Constitution VI.
        # Now we surface it as a verbatim warning, attach the canonical
        # disclaimer to the fallback memo (Constitution IV is invariant),
        # and let the analyze findings (if any survived) reach the
        # lawyer. The "Findings (if any) are still valid." line is the
        # honest signal that the summary failed but the upstream work
        # was not wasted.
        warnings.append(
            f"Client summary: Ollama timed out after "
            f"{exc.elapsed_seconds:.1f}s. The summary stage is the longest "
            "in the pipeline; cold-start or overwhelmed model can exceed "
            "timeout. Findings (if any) are still valid."
        )
        return (
            ClientSummary(
                what_this_contract_is=_TOTAL_FALLBACK,
                what_youre_committing_to=_TOTAL_FALLBACK,
                biggest_risks=(),
                recommendation=_TOTAL_FALLBACK,
            ),
            tuple(warnings),
        )

    summary = ClientSummary(
        what_this_contract_is=_coerce_text(payload.get("what_this_contract_is")),
        what_youre_committing_to=_coerce_text(payload.get("what_youre_committing_to")),
        biggest_risks=_coerce_risks(payload.get("biggest_risks")),
        recommendation=_coerce_text(payload.get("recommendation")),
    )

    # Per-field silence: the model parsed but omitted (or emptied) one or
    # more narrative fields. List the offending field names so the lawyer
    # can decide whether to rerun (e.g. on the larger model) or accept the
    # partial summary. ``biggest_risks`` is intentionally excluded — an
    # empty risks tuple is a legitimate "no material risks" signal per the
    # ClientSummary docstring, not a fallback.
    fallback_fields = [
        name
        for name, value in (
            ("what_this_contract_is", summary.what_this_contract_is),
            ("what_youre_committing_to", summary.what_youre_committing_to),
            ("recommendation", summary.recommendation),
        )
        if value == _FIELD_FALLBACK
    ]
    if fallback_fields:
        warnings.append(
            "Client summary: model omitted or left empty: "
            f"{', '.join(fallback_fields)}. Each missing field shows a "
            "fallback placeholder."
        )

    return summary, tuple(warnings)
