"""Client-summary pipeline stage — the four-section plain-English memo.

Calls Ollama once to produce a four-field JSON memo for a non-lawyer
client, then attaches the constitutional disclaimer.

Constitution IV — Disclaimers are part of the product
-----------------------------------------------------
The disclaimer is a non-removable, server-side constant
(:data:`DISCLAIMER_TEXT`). The model NEVER generates it; the prompt in
:mod:`caveat.llm.prompts` explicitly forbids the model from authoring,
paraphrasing, or omitting one. This module is the single place the
disclaimer is attached, so the audit trail for "did this output ship with
a disclaimer" is one ``grep``.

Per Constitution I, all network I/O is funnelled through
:mod:`caveat.llm.ollama_client`. Per Constitution VI, malformed model
output is surfaced as a fallback memo with the disclaimer still attached
— the lawyer sees that the summary failed; we do not pretend it
succeeded.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import asdict, dataclass

from caveat.llm import ollama_client
from caveat.llm.prompts import build_client_summary_prompt
from caveat.pipeline.validate_citations import Finding

DISCLAIMER_TEXT = (
    "This summary was generated by Caveat AI, an AI tool. It is intended to "
    "support, not replace, attorney review. The attorney remains responsible "
    "for the final work product."
)
"""The non-removable disclaimer, attached to every :class:`ClientSummary`.

Constitution IV: every generated output ships with this. There is no flag
to disable it; it is a default value on the dataclass field below."""

_FIELD_FALLBACK = "(Not available — model output incomplete.)"
_TOTAL_FALLBACK = "(Summary unavailable — model returned malformed output.)"
_MAX_RISKS = 3


@dataclass(slots=True, frozen=True)
class ClientSummary:
    """The four-section client-facing memo plus the constitutional disclaimer.

    ``biggest_risks`` holds up to :data:`_MAX_RISKS` strings (we trim if
    the model returns more). An empty tuple is acceptable: it means the
    model could not identify any material risks, which is a real signal
    and not a bug.
    """

    what_this_contract_is: str
    what_youre_committing_to: str
    biggest_risks: tuple[str, ...]
    recommendation: str
    disclaimer: str = DISCLAIMER_TEXT


def _coerce_text(value: object) -> str:
    """Return *value* as a non-empty string or :data:`_FIELD_FALLBACK`."""
    if isinstance(value, str) and value.strip():
        return value
    return _FIELD_FALLBACK


def _coerce_risks(value: object) -> tuple[str, ...]:
    """Coerce the model's ``biggest_risks`` field into at most :data:`_MAX_RISKS`."""
    if not isinstance(value, list):
        return ()
    risks: list[str] = []
    for item in value:
        if isinstance(item, str) and item.strip():
            risks.append(item)
        if len(risks) == _MAX_RISKS:
            break
    return tuple(risks)


def build_client_summary(
    findings: Iterable[Finding],
    contract_type: str,
    source_text: str,
) -> ClientSummary:
    """Generate the client-facing memo for *contract_type* given *findings*.

    The findings are converted to plain dicts for the prompt (the model
    receives the same shape regardless of the dataclass implementation
    behind it). The disclaimer is attached unconditionally — even on
    malformed-JSON failure paths — because that is the constitutional
    invariant.
    """
    findings_dicts = [asdict(f) for f in findings]
    prompt = build_client_summary_prompt(findings_dicts, contract_type, source_text)

    try:
        payload = ollama_client.generate_json(prompt)
    except ollama_client.OllamaInvalidJSONError:
        return ClientSummary(
            what_this_contract_is=_TOTAL_FALLBACK,
            what_youre_committing_to=_TOTAL_FALLBACK,
            biggest_risks=(),
            recommendation=_TOTAL_FALLBACK,
        )

    return ClientSummary(
        what_this_contract_is=_coerce_text(payload.get("what_this_contract_is")),
        what_youre_committing_to=_coerce_text(payload.get("what_youre_committing_to")),
        biggest_risks=_coerce_risks(payload.get("biggest_risks")),
        recommendation=_coerce_text(payload.get("recommendation")),
    )
